#!/usr/bin/env node
/** Project-local intent records. Node standard library only; never commits or spawns agents. */
import { createHash, randomUUID } from 'node:crypto';
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync,
  renameSync, rmdirSync, unlinkSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const STATUSES = new Set(['draft', 'active', 'fulfilled', 'abandoned', 'superseded']);
const KEYS = ['schema', 'id', 'status', 'revision', 'source', 'revision_source', 'created', 'updated',
  'approval', 'approved_sha256', 'closure_evidence', 'superseded_by'];
const INDEX_BANNER = '<!-- Generated by work-intent. Navigation only; intent.md is authoritative. -->';
const fail = message => { throw new Error(message); };
const sha256 = data => createHash('sha256').update(data).digest('hex');
const nonempty = value => typeof value === 'string' && value.trim().length > 0;
const validID = id => typeof id === 'string' && /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/.test(id);
const validSHA = sha => typeof sha === 'string' && /^[a-f0-9]{64}$/.test(sha);
const posix = value => value.split(path.sep).join('/');

function assertID(id) { if (!validID(id)) fail('id must be 1–80 ASCII letters, digits, _ or -, starting with a letter/digit'); }
function canonicalBody(body) { return body.replace(/\r\n/g, '\n').trim() + '\n'; }
function validateBody(body) {
  if (!/^# Intent: .+$/m.test(body)) fail('body needs a # Intent: title');
  for (const heading of ['Problem', 'Proposed outcome', 'Constraints', 'Open questions']) {
    const part = body.match(new RegExp(`^## ${heading}\\s*\\n([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, 'm'));
    if (!part || !part[1].trim()) fail(`body needs a nonempty ## ${heading} section`);
  }
}
function validateMeta(meta) {
  if (KEYS.some(k => !(k in meta)) || Object.keys(meta).some(k => !KEYS.includes(k))) fail('unexpected or missing metadata keys');
  if (meta.schema !== 1) fail('unsupported intent schema');
  assertID(meta.id);
  if (!STATUSES.has(meta.status)) fail('unknown intent status');
  if (!Number.isSafeInteger(meta.revision) || meta.revision < 1) fail('revision must be a positive safe integer');
  for (const k of ['source', 'created', 'updated']) if (!nonempty(meta[k])) fail(`${k} must be nonempty`);
  for (const k of ['revision_source', 'approval', 'closure_evidence', 'superseded_by']) {
    if (meta[k] !== null && !nonempty(meta[k])) fail(`${k} must be null or a nonempty string`);
  }
  if (meta.approved_sha256 !== null && !validSHA(meta.approved_sha256)) fail('invalid approved_sha256');
  if (meta.status === 'draft' && (meta.approval !== null || meta.approved_sha256 !== null)) fail('draft must not retain approval');
  if (['active', 'fulfilled'].includes(meta.status) && (!nonempty(meta.approval) || !validSHA(meta.approved_sha256))) fail('active/fulfilled intent requires approval and approved digest');
  if (['draft', 'active'].includes(meta.status) && (meta.closure_evidence !== null || meta.superseded_by !== null)) fail('open intent cannot carry closure');
  if (['fulfilled', 'abandoned', 'superseded'].includes(meta.status) && !nonempty(meta.closure_evidence)) fail('closed intent requires closure_evidence');
  if (meta.status === 'superseded') assertID(meta.superseded_by);
  else if (meta.superseded_by !== null) fail('superseded_by is only valid for superseded intent');
}
export function decode(text) {
  // Deliberately small YAML subset: one scalar per line, emitted as JSON literals.
  const match = text.replace(/\r\n/g, '\n').match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) fail('expected scalar YAML frontmatter followed by Markdown; use the template/helper');
  const meta = Object.create(null);
  for (const line of match[1].split('\n')) {
    const pair = line.match(/^([a-z_][a-z_0-9]*):\s*(.+)$/);
    if (!pair || !KEYS.includes(pair[1]) || pair[1] in meta) fail(`invalid or duplicate metadata line: ${line}`);
    try { meta[pair[1]] = JSON.parse(pair[2]); }
    catch { meta[pair[1]] = pair[2]; }
  }
  const body = canonicalBody(match[2]);
  validateMeta(meta); validateBody(body);
  return { meta, body };
}
function encode(meta, body) {
  validateMeta(meta); validateBody(body);
  return `---\n${KEYS.map(k => `${k}: ${JSON.stringify(meta[k])}`).join('\n')}\n---\n\n${canonicalBody(body)}`;
}
function approvalDigest({ meta, body }) {
  return sha256(JSON.stringify({ id: meta.id, revision: meta.revision, source: meta.source, revision_source: meta.revision_source, body }));
}
function verifyApproval(record) {
  if (record.meta.approved_sha256 !== null && record.meta.approved_sha256 !== approvalDigest(record)) {
    fail('approved content changed; return to draft with revise and obtain approval for that revision');
  }
}

export class IntentStore {
  constructor(workspace, home = 'intent') {
    if (!nonempty(workspace)) fail('--workspace is required (the lead’s canonical project root)');
    this.workspace = realpathSync(path.resolve(workspace));
    if (!nonempty(home) || path.isAbsolute(home) || home.split(/[\\/]/).some(p => !p || p === '.' || p === '..')) fail('home must be a project-relative directory without . or ..');
    this.home = home.split(/[\\/]/).join(path.sep);
    this.root = this.safe(this.home);
  }
  safe(relative) {
    const parts = relative.split(path.sep);
    let target = this.workspace;
    for (const part of parts) {
      if (!part || part === '.' || part === '..') fail('invalid relative path');
      target = path.join(target, part);
      // Reject links even when dangling; all writes stay under the explicit workspace.
      try { if (lstatSync(target).isSymbolicLink()) fail(`symlink is not an intent home: ${target}`); }
      catch (error) { if (error.code !== 'ENOENT') throw error; }
    }
    return target;
  }
  filename(id) { assertID(id); return this.safe(path.join(this.home, id, 'intent.md')); }
  read(id) {
    const filename = this.filename(id);
    const text = readFileSync(filename, 'utf8');
    const record = decode(text);
    if (record.meta.id !== id) fail(`directory/id mismatch: ${id}`);
    return { ...record, sha256: sha256(text), path: posix(path.relative(this.workspace, filename)) };
  }
  list({ all = false } = {}) {
    this.safe(this.home);
    if (!existsSync(this.root)) return [];
    const records = [], ids = new Set();
    for (const entry of readdirSync(this.root, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (entry.name.startsWith('.') || entry.name === 'INDEX.md') continue;
      if (entry.isSymbolicLink()) fail(`symlink in intent home: ${entry.name}`);
      if (!entry.isDirectory()) continue;
      const filename = this.filename(entry.name);
      if (!existsSync(filename)) continue;
      const rec = this.read(entry.name);
      if (ids.has(rec.meta.id.toLowerCase())) fail(`case-insensitive duplicate id: ${rec.meta.id}`);
      ids.add(rec.meta.id.toLowerCase());
      // Do not hide broken active records just because the index was previously valid.
      verifyApproval(rec);
      if (all || ['draft', 'active'].includes(rec.meta.status)) records.push(rec);
    }
    return records;
  }
  locked(callback) {
    this.safe(this.home); mkdirSync(this.root, { recursive: true });
    const lock = this.safe(path.join(this.home, '.intent.lock'));
    try { mkdirSync(lock); }
    catch (error) { if (error.code === 'EEXIST') fail('intent home is locked; retry after the writer finishes (inspect a stale .intent.lock, never auto-delete it)'); throw error; }
    try { return callback(); } finally { rmdirSync(lock); }
  }
  write(id, meta, body) {
    const filename = this.filename(id), directory = path.dirname(filename);
    mkdirSync(directory, { recursive: true });
    const temp = this.safe(path.join(this.home, id, `.intent-${randomUUID()}.tmp`));
    try { writeFileSync(temp, encode(meta, body), { flag: 'wx', mode: 0o644 }); renameSync(temp, filename); }
    finally { if (existsSync(temp)) unlinkSync(temp); }
    return this.read(id);
  }
  create({ id, source, body }) {
    assertID(id); if (!nonempty(source)) fail('source must cite the initiating user request or authoritative record');
    body = canonicalBody(body); validateBody(body);
    return this.locked(() => {
      if (existsSync(this.filename(id)) || this.list({ all: true }).some(r => r.meta.id.toLowerCase() === id.toLowerCase())) fail(`intent already exists: ${id}; read/reuse it`);
      const now = new Date().toISOString();
      return this.write(id, { schema: 1, id, status: 'draft', revision: 1, source,
        revision_source: null, created: now, updated: now, approval: null, approved_sha256: null,
        closure_evidence: null, superseded_by: null }, body);
    });
  }
  check(id, { expect, active = false } = {}) {
    const rec = this.read(id);
    if (expect !== undefined && (!validSHA(expect) || rec.sha256 !== expect)) fail('stale intent reference; reread the canonical record before continuing');
    verifyApproval(rec);
    if (active && rec.meta.status !== 'active') fail(`intent is ${rec.meta.status}, not active`);
    return rec;
  }
  change(id, expect, operation) {
    if (!validSHA(expect)) fail('mutation requires --expect with the SHA-256 returned by read/list');
    return this.locked(() => {
      // revise may recover manually edited active content, but still requires its current hash.
      const rec = this.read(id);
      if (rec.sha256 !== expect) fail('stale intent reference; reread before writing');
      const changed = operation(rec);
      changed.meta.updated = new Date().toISOString();
      return this.write(id, changed.meta, changed.body);
    });
  }
  revise(id, { expect, source, body }) {
    if (!nonempty(source)) fail('revision needs a source/reason; a new session is not a new intent');
    body = canonicalBody(body); validateBody(body);
    return this.change(id, expect, rec => {
      if (rec.meta.status === 'superseded') fail('follow superseded_by instead of reviving an obsolete record');
      return { body, meta: { ...rec.meta, status: 'draft', revision: rec.meta.revision + 1,
        revision_source: source, approval: null, approved_sha256: null, closure_evidence: null, superseded_by: null } };
    });
  }
  activate(id, { expect, approval }) {
    if (!nonempty(approval)) fail('approval must cite the actual human instruction/review, never silence');
    return this.change(id, expect, rec => {
      if (rec.meta.status !== 'draft') fail('only draft intent can be activated');
      return { ...rec, meta: { ...rec.meta, status: 'active', approval, approved_sha256: approvalDigest(rec) } };
    });
  }
  close(id, { expect, status, evidence, supersededBy = null }) {
    if (!['fulfilled', 'abandoned', 'superseded'].includes(status) || !nonempty(evidence)) fail('close requires a terminal status and real evidence/reason');
    if (status !== 'superseded' && supersededBy !== null) fail('--superseded-by requires superseded status');
    return this.change(id, expect, rec => {
      verifyApproval(rec);
      if (!['draft', 'active'].includes(rec.meta.status)) fail('intent is already closed');
      if (status === 'fulfilled' && rec.meta.status !== 'active') fail('only active intent can be fulfilled');
      if (status === 'superseded') {
        if (supersededBy === id) fail('intent cannot supersede itself');
        this.check(supersededBy, { active: true });
      }
      return { ...rec, meta: { ...rec.meta, status, closure_evidence: evidence, superseded_by: supersededBy } };
    });
  }
  index({ write = false } = {}) {
    const render = () => {
      const escape = s => s.replace(/\|/g, '\\|').replace(/[\r\n]/g, ' ');
      const lines = [INDEX_BANNER, '# Intent index', '', 'Regenerate with `intent.mjs index --write`. Use `list` for a live view.', ''];
      const all = this.list({ all: true });
      for (const [heading, keep] of [['Current', r => ['draft', 'active'].includes(r.meta.status)], ['History', r => !['draft', 'active'].includes(r.meta.status)]]) {
        lines.push(`## ${heading}`, '', '| Intent | Status | Revision | Outcome |', '|---|---|---|---|');
        for (const rec of all.filter(keep)) {
          const title = rec.body.match(/^# Intent: (.+)$/m)[1];
          lines.push(`| [${rec.meta.id}](${rec.meta.id}/intent.md) | ${rec.meta.status} | ${rec.meta.revision} | ${escape(title)} |`);
        }
        lines.push('');
      }
      return lines.join('\n');
    };
    if (!write) return render();
    return this.locked(() => {
      const filename = this.safe(path.join(this.home, 'INDEX.md'));
      if (existsSync(filename) && !readFileSync(filename, 'utf8').startsWith(INDEX_BANNER)) fail('refusing to replace a handwritten INDEX.md');
      const content = render(), temp = this.safe(path.join(this.home, `.index-${randomUUID()}.tmp`));
      try { writeFileSync(temp, content, { flag: 'wx' }); renameSync(temp, filename); }
      finally { if (existsSync(temp)) unlinkSync(temp); }
      return content;
    });
  }
}
export function reference(rec) { return { id: rec.meta.id, path: rec.path, revision: rec.meta.revision, sha256: rec.sha256 }; }
const HELP = `Usage: node intent.mjs COMMAND --workspace /project [--home intent] [options]
  list [--all]                       Read current records; no files created
  read --id ID                      Record, body and exact intent_ref
  create --id ID --source REF --body FILE
  revise --id ID --expect SHA --source REF --body FILE
  activate --id ID --expect SHA --approval REF
  check --id ID [--expect SHA] [--active]
  close --id ID --expect SHA --status fulfilled|abandoned|superseded --evidence REF [--superseded-by ID]
  index [--write]                    Derived navigation; never authority
Body files contain Markdown only. Approval strings record, not authenticate, a human decision.
No command stages/commits files, generates a spec/plan, spawns a team, or edits another project.`;
export function main(argv) {
  if (!argv.length || argv.includes('--help')) return HELP;
  const command = argv.shift(), args = {};
  const allowed = {
    list: ['all'], read: ['id'], create: ['id', 'source', 'body'], revise: ['id', 'expect', 'source', 'body'],
    activate: ['id', 'expect', 'approval'], check: ['id', 'expect', 'active'],
    close: ['id', 'expect', 'status', 'evidence', 'superseded-by'], index: ['write'],
  };
  if (!Object.hasOwn(allowed, command)) fail(`unknown command: ${command}`);
  for (let i = 0; i < argv.length; i++) {
    const key = argv[i].replace(/^--/, '');
    if (!argv[i].startsWith('--') || !['workspace', 'home', ...allowed[command]].includes(key) || key in args) fail(`unexpected/duplicate option: ${argv[i]}`);
    if (['all', 'active', 'write'].includes(key)) args[key] = true;
    else { if (!argv[i + 1] || argv[i + 1].startsWith('--')) fail(`missing value for --${key}`); args[key] = argv[++i]; }
  }
  const store = new IntentStore(args.workspace, args.home);
  const body = () => { if (!args.body) fail('--body is required'); return readFileSync(args.body, 'utf8'); };
  if (command === 'index') return store.index({ write: args.write });
  if (command === 'list') return store.list({ all: args.all }).map(rec => ({ intent_ref: reference(rec), status: rec.meta.status, source: rec.meta.source, title: rec.body.match(/^# Intent: (.+)$/m)[1] }));
  let record;
  if (command === 'read') record = store.read(args.id);
  if (command === 'check') record = store.check(args.id, { expect: args.expect, active: args.active });
  if (command === 'create') record = store.create({ id: args.id, source: args.source, body: body() });
  if (command === 'revise') record = store.revise(args.id, { expect: args.expect, source: args.source, body: body() });
  if (command === 'activate') record = store.activate(args.id, { expect: args.expect, approval: args.approval });
  if (command === 'close') record = store.close(args.id, { expect: args.expect, status: args.status, evidence: args.evidence, supersededBy: args['superseded-by'] });
  return { intent_ref: reference(record), ...record.meta, body: record.body };
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { const output = main(process.argv.slice(2)); console.log(typeof output === 'string' ? output : JSON.stringify(output, null, 2)); }
  catch (error) { console.error(`intent: ${error.message}`); process.exitCode = 1; }
}
